---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:

 - type: files
   files:
     - source: base-files
       destination: /

     - source: kde-settings
       destination: /

 - type: script
   snippets:
      - "systemctl enable plasma-setup.service"
      - "systemctl enable plasmalogin.service"

   scripts:
      - set-kde-wallpapers.sh
      - remove-fedora-branding.sh
