---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:

 - type: files
   files:
     - source: base-files
       destination: /

     - source: kde-settings
       destination: /

     - source: sddm-config
       destination: /

 - type: script
   snippets:
      - "systemctl enable zodium-default-flatpak.service"

   scripts:
      - set-default-wallpapers.sh